[package]
name = "thief"
version = "0.1.0"
authors = ["inkyu <gofiri@gmail.com>"]

[lib]
name = "proc_macros"
crate-type = ["proc-macro"]

[dependencies]
libc = "0.2"
syn = "0.10.5"
quote = "0.3.10"

