[package]
name = "thief"
version = "0.1.0"
authors = ["inkyu <gofiri@gmail.com>"]

[lib]
name = "proc_macros"
crate-type = ["proc-macro"]

[dependencies]
syntect = "*"
libc = "*"
syn = "*"
quote = "*"
